version: '3.8'

services:
  # pdf-converter:
  #   image: registry.rtuitlab.dev/rtuitlab/ouch-r/pdf-parser
  #   networks:
  #     - net
  api-bot:
    image: registry.rtuitlab.dev/rtuitlab/ouch-r/bot
    environment:
      - VkBotOptions__GroupId=${VK_GROUP_ID}
      - VkBotOptions__GroupAccessToken=${VK_ACCESS_TOKEN}
      - CalendarOptions__GoogleCalendarUrl=${ICS_CALENDAR_URL}
  site:
    image: registry.rtuitlab.dev/rtuitlab/ouch-r/site
  proxy:
    image: registry.rtuitlab.dev/rtuitlab/ouch-r/proxy
